name: TEST CI
 on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # Execute unit tests
      - name: Unit Tests
        run: cd packages/cli && npm run test
