name: TEST CI
on:
  pull_request:
    branches:
      - dev
jobs:
  GET-MATRIX:
    runs-on: ubuntu-latest
    outputs:
      matrix-packages: ${{ steps.packages_list.outputs.matrix-packages }}
    steps:
      - name: get packages names in array
        id: packages_list
        run: |
          cd $GITHUB_WORKSPACE && cd ../ && echo pwd && echo "::set-output name=matrix-packages::$(ls|jq -cnR '[inputs | select(length>0)]')"
  PACKAGES-TEST:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    needs: GET-MATRIX
    strategy:
      matrix:
        packages: ${{ fromJson(needs.GET-MATRIX.outputs.matrix-packages) }}
    steps:
      - uses: actions/checkout@v2
      - name: Define the Envs
        run: |
          echo "PACKAGE=${{ matrix.packages }}" >> $GITHUB_ENV
          echo "KIND=packages" >> $GITHUB_ENV
          echo "::set-env name=PYTHONPATH::${PYTHONPATH}:$GITHUB_WORKSPACE/ops/github-actions"
      - name: Install the package && Run the test
        run: |
            apt install python3.8 && python3 $GITHUB_WORKSPACE/ops/github-actions/unittest/install-and-tests.py
#
