name: TEST CI
on:
  pull_request:
    branches:
      - dev
jobs:
  GET-MATRIX:
    runs-on: ubuntu-latest
    outputs:
      matrix-packages: ${{ steps.packages_list.outputs.matrix-packages}}
    steps:
      - uses: actions/checkout@v2
      - name: get packages names in array
        id: packages_list
        run: |
          cd $GITHUB_WORKSPACE/packages && echo "::set-output name=matrix-packages::$(ls|jq -cnR '[inputs | select(length>0)]')"

  PACKAGES-TEST:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      NODE_ENV: development
      PACKAGE: ${{ matrix.packages }}
      RELEAI_FS_API_KEY: ${{ secrets.FS_DEV_API_KEY }}
    needs: GET-MATRIX
    strategy:
      matrix:
        packages: ${{ fromJson(needs.GET-MATRIX.outputs.matrix-packages) }}
        exclude:
        - packages: README.md
    steps:
      - uses: actions/checkout@v2
      - name: Install the package && Run the test
        run: |
          pip3 install ${{ secrets.GIT_UTILS_REPO }}
          cd packages/$PACKAGE && python3 $GITHUB_WORKSPACE/ops/github-actions/unittest/install-and-tests.py
